let tests run through
there is still an issue with the second PluginTestCase:
it doesn't run because the previous one doesn't clean up properly:

FixtureError: 'AiiDA dbenv can not be loaded while creating a test profile'