fix '_use_methods' bug
Actually, an undefined function in the _use_methods dict caused
no _use_methods to be set.
The aiida error message should definitely be improved.

For the moment, I just deposit it here:

  File "/Users/leopold/Applications/miniconda3/envs/aiida_zeopp/lib/python2.7/site-packages/aiida/orm/implementation/general/calculation/__init__.py", line 209, in __getattr__
    for k in self._use_methods.iterkeys()])
  File "/Users/leopold/Applications/miniconda3/envs/aiida_zeopp/lib/python2.7/site-packages/aiida/orm/implementation/general/calculation/__init__.py", line 153, in __getattr__
    raise AttributeError("'{0}' object has no attribute '{1}'".format(type(self), name))
AttributeError: '<class 'aiida_zeopp.calculations.network.NetworkCalculation'>' object has no attribute '_use_methods'